*create my sample dataset;
data File;
length ptype $ 3 stype $ 3 sbudef $ 3 trsrel $ 3 cisrel $ 3 ;
input hhldid acctnum  custkey   branch  ptype $  stype $  balance sbudef $  trsrel $  cisrel $  ssnprim  ssnsec ;
datalines;
1111111111 12345 1111111111 00123 DDA RE5 400000 CON xxx JNT 123456789 987654321
1111111111 12345 1111111111 00123 DDA RE5 400000 CON xxx JNT 987654321 123456789
;
run;

data file;
set file;
IF SSNPRIM IN (.,0,999999999,111111111) THEN DO;
   SSNPRIM = SSNSEC;
   SSNSEC = .;
END;

IF SSNPRIM IN (.,0,999999999,111111111) THEN PRMSSFLG = 'N';
                                        ELSE PRMSSFLG = 'Y';

IF SSNSEC IN (.,0,999999999,111111111) THEN SECSSFLG = 'N';
                                       ELSE SECSSFLG = 'Y';

IF (SECSSFLG = 'N' AND CISREL IN ('JT1','JNT')) THEN CISREL = '???';
IF (SECSSFLG = 'Y' AND CISREL not IN ('JT1','JNT','CRP'))
                                                THEN CISREL = 'JNT';
run;


DATA NATSNG NATSNGNS NATJNT NATJNTNS MNTSNG MNTSNGNS MNTJNT MNTJNTNS NATIRA NATIRANS MNTIRA MNTIRANS; 
SET FILE;
 IF (SBUDEF = 'NTL' AND PTYPE ne 'IRA') THEN DO;
   IF (CISREL not IN('JT1','JNT') AND PRMSSFLG = 'Y') THEN OUTPUT NATSNG;
   IF (CISREL not IN('JT1','JNT') AND PRMSSFLG = 'N') THEN OUTPUT NATSNGNS;
   IF (CISREL IN('JT1','JNT') AND PRMSSFLG = 'Y') THEN OUTPUT NATJNT;
   IF (CISREL IN('JT1','JNT') AND PRMSSFLG = 'N') THEN OUTPUT NATJNTNS;
 END;
 IF (SBUDEF = 'NTL' AND PTYPE = 'IRA') THEN DO;
   IF PRMSSFLG = 'Y' THEN OUTPUT NATIRA;
   IF PRMSSFLG = 'N' THEN OUTPUT NATIRANS;
 END;
 IF (SBUDEF ne 'NTL' AND PTYPE ne 'IRA') THEN DO;
   IF (CISREL not IN('JT1','JNT') AND PRMSSFLG = 'Y') THEN OUTPUT MNTSNG;
   IF (CISREL not IN('JT1','JNT') AND PRMSSFLG = 'N') THEN OUTPUT MNTSNGNS;
   IF (CISREL IN('JT1','JNT') AND PRMSSFLG = 'Y') THEN OUTPUT MNTJNT;
   IF (CISREL IN('JT1','JNT') AND PRMSSFLG = 'N') THEN OUTPUT MNTJNTNS;
 END;
 IF (SBUDEF ne 'NTL' AND PTYPE = 'IRA') THEN DO;
   IF PRMSSFLG = 'Y' THEN OUTPUT MNTIRA;
   IF PRMSSFLG = 'N' THEN OUTPUT MNTIRANS;
 END;
run;


DATA MNTJNT1; SET MNTJNT; run;
PROC SORT DATA = MNTJNT; BY SSNPRIM; run;

DATA MNTJNT; 
SET MNTJNT; 
RETAIN CUSTBAL;
BY SSNPRIM;
BALANCE = BALANCE/2;
IF FIRST.SSNPRIM THEN CUSTBAL = 0;
CUSTBAL + BALANCE;
IF LAST.SSNPRIM THEN DO;
   IF CUSTBAL > 250000 then TYPE = 'MNTJNT  ';
   OUTPUT;
END;
KEEP TYPE SSNPRIM SSNSEC CUSTKEY CUSTBAL;
run;

PROC SORT DATA = MNTJNT1; BY SSNSEC; run;

DATA MNTJNT1; 
SET MNTJNT1; 
BY SSNSEC;
RETAIN CUSTBAL;
   BALANCE = BALANCE/2;
IF FIRST.SSNSEC THEN CUSTBAL = 0; 
   CUSTBAL + BALANCE;
IF LAST.SSNSEC THEN DO;
   IF CUSTBAL > 250000 then TYPE = 'MNTJNT  ';
   OUTPUT;
END;
   KEEP TYPE SSNPRIM SSNSEC CUSTKEY CUSTBAL;
run;

DATA MNTJNT; SET MNTJNT MNTJNT1; run;


PROC FREQ DATA = MNTJNT; 
TABLES TYPE/LIST MISSING;
run;
