libname myxls oledb init_string="Provider=Microsoft.ACE.OLEDB.12.0;        Data Source=C:\Documents and Settings\ewnym5s\My Documents\FWorks_20121004.xls;        Extended Properties=Excel 12.0";
data myxls.segment;
set work.segment_results;
run;
data myxls.cbr;
set work.cbr_results;
run;
data myxls.market;
set work.market_results;
run;
data myxls.band;
set work.band_results;
run;
data myxls.tenure_yr;
set work.tenure_yr_results;
run;
data myxls.svcs;
set work.svcs_results;
run;
data myxls.cqi;
set work.cqi_results;
run;
data myxls.cqi_dd;
set work.cqi_dd_results;
run;
data myxls.cqi_bp;
set work.cqi_bp_results;
run;
data myxls.cqi_web;
set work.cqi_web_results;
run;
data myxls.cqi_deb;
set work.cqi_deb_results;
run;
data myxls.cqi_odl;
set work.cqi_odl_results;
run;
data myxls.RM;
set work.RM_results;
run;
data myxls.bal3;
set work.bal3;
run;
data myxls.clv4;
set work.clv4;
run;
data myxls.ixi4;
set work.ixi4;
run;
data myxls.tran3;
set work.tran3;
run;
data myxls.web3;
set work.web3;
run;
